### ISSUE TITLE
The hardest programming problem

### ISSUE THREAD

**Issue by Ptico** [Ptico/inflecto#1]
@abinoam looks like we need some new name, any suggestions?

**Comment by abinoam** [comment]
I'm better at cache invalidation and off-by-one errors 😁

**Comment by abinoam** [comment]
Let's think about the name. Inflector is how ActiveSupport calls its module.
There's an ActiveSupport::Inflector::Inflections module also.

There's no wikipedia page for Inflecto. But there's one for Inflection https://en.wikipedia.org/wiki/Inflection

I've made a selection of the sister wikipedia pages that has no diacritics. Unfortunately, neither portuguese nor ucranian fits this (no diacritics) criteria.

Beegenge https://stq.wikipedia.org/wiki/Beegenge
Ffurfiant https://cy.wikipedia.org/wiki/Ffurfiant
Fleksie (Verbuigin of fleksie) https://af.wikipedia.org/wiki/Verbuiging
Fleksija https://lv.wikipedia.org/wiki/Fleksija_(valodniec%C4%ABba)
Fleksio https://eo.wikipedia.org/wiki/Fleksio
Fleksja https://pl.wikipedia.org/wiki/Fleksja
Flessione https://it.wikipedia.org/wiki/Flessione_(linguistica)
Flexie https://nl.wikipedia.org/wiki/Flexie_(taalkunde)
Flexio https://eu.wikipedia.org/wiki/Flexio
Flexion https://bar.wikipedia.org/wiki/Flexion
Flexion https://de.wikipedia.org/wiki/Flexion
Flexion https://fr.wikipedia.org/wiki/Flexion_(linguistique)
Flexiono https://io.wikipedia.org/wiki/Flexiono
Flexiune https://ro.wikipedia.org/wiki/Flexiune
Flexura https://la.wikipedia.org/wiki/Flexura
Flexus
Taivutus https://fi.wikipedia.org/wiki/Taivutus_(kielioppi)

It seems like something beginning with "Flex" would fit well for the gem name.

I've had a look a latin dictionary http://www.perseus.tufts.edu/hopper/resolveform?type=start&lookup=flex&lang=la

I saw **flexo** at the latin dict. It says it means "to bend".
Flexo reads well in portuguese. And it means BENT or that could be bent in portuguese. BUT... the name is already taken https://rubygems.org/search?query=flexo

Another good option is Flexus, and it's available at rubygems. See https://rubygems.org/search?query=flexu
See it https://en.wiktionary.org/wiki/flexus

So my first suggestion is Flexus!

```ruby
Flexus.singularize("cars")
```

**Comment by Ptico** [comment]
Wow, that's good. I only thought on something general like `StringTool`

**Comment by pabloh** [comment]
What about asking the gem ownership from the original author?

**Comment by abinoam** [comment]
Hi @pabloh,

We have already done so. We've found that the best way was let inflecto where it is because there's tons of libs that depend on that. 

This was discussed at https://github.com/mbj/inflecto/issues/10

**Comment by abinoam** [comment]
@Ptico,

Let's go with **Flexus** ?

**Comment by pabloh** [comment]
@abinoam, I see, I thought that maybe releasing a new mayor version could do the trick as well.

**Comment by abinoam** [comment]
We have discussed this option too. @Ptico , @mbj and I have agreed to fork.
There will be less resolution conflict.
If you're lib depends on an old lib that depend on inflecto, you're stuck, and will not be able to use inflecto new versions.
With the fork, you can use ForkedInflecto version 2 while the gem you're depending on may be using OriginalInflecto 0.0.2.

**Comment by pabloh** [comment]
Cool.

2017-11-02 10:20 GMT-03:00 Abinoam P. Marques Jr. <notifications@github.com>
:

**Comment by Ptico** [comment]
@abinoam Agree
