### ISSUE TITLE
What is the lowest ruby version are we going to support?

### ISSUE THREAD

**Issue by abinoam** [Ptico/inflecto#14]
Note: https://en.wikipedia.org/wiki/Ruby_(programming_language)#Table_of_versions

We already have inflecto supporting old ruby versions. It's working, reliable and it will freeze (not break at near future).
I think we shouldn't loose time trying to keep compatible with old rubies. We should aim for the future. (But I'm open for suggestions).

2.1 has already ended security maintenance phase since 2017-03-31. It means NO SUPPORT at all from Ruby core team.
2.2 ended support phase since 2017-03-28 and it'll end security maintenance phase in 4 months (2018-03-31).
So we should focus on 2.3, 2.4, 2.5.

My suggestion, we should do a release of 1.0.x with all these things that were around inflecto but unreleased. So, most people could just jump into flexus without any problem.

Then, we begin a 2.0.x branch, where the required ruby version will be >= 2.3.

What do you think @Ptico .

**Comment by abinoam** [comment]
@Ptico, now that we have a roadmap with 1.0.x and 2.0.x.
I think this question is related to 2.0.x
What the lowest Ruby version should we support on 2.0.x?

**Comment by Ptico** [comment]
>= 2.3 i think

**Comment by abinoam** [comment]
Completely agree (as I discussed above).
