### ISSUE TITLE
Give an option for global state

### ISSUE THREAD

**Issue by abinoam** [Ptico/inflecto#19]
Global state is evil!

We should give a per instance option for users of Flexus.

> I recommend to avoid any API that does global state mutations. Provide a default instance, and all project specific settings create new ones
> - @mbj

Source: https://twitter.com/_m_b_j_/status/926476875186278400

> Good news. I can’t check soon, but it looks like it uses global state, which is the current problem that we have w/ inflecto.
> - @jodosha

Source: https://twitter.com/jodosha/status/926535090188021760

**Comment by mbj** [comment]
> Global state is evil!

Note I meant: mutable global state.

`Flexus` as the toplevel module is by definition also global state, but its not mutable (unless reflection and metaprogramming is done, I deliberately exclude here).

**Comment by abinoam** [comment]
Yes, much more detailed definition. 👍

**Comment by jodosha** [comment]
Thanks for bringing the discussion here, which it's an appropriate place.

---

The problem with the global state for a lib like Flexus/Inflecto are the exceptions to the pluralization rules. Once they are set, `Flexus.pluralize` will use the singleton instance that has that exceptions to pluralize a string.

If a program during its execution modifies that rules, `.pluralize` isn't deterministic anymore:

```ruby
require "flexus"

Flexus.pluralize("human")
  # => "humen"

# At this point I expect that for the entire program lifetime, Flexus will return the same result over and over

# But I can mutate the global registry of exception rules:
Flexus.inflections { |i| i.plural("human", "humans") }

# And now it returns a different result:
Flexus.pluralize("human")
  # => "humans"

# I fixed the pluralization, but it can be mutated again with potentially wrong results:
Flexus.inflections { |i| i.plural("human", "foo") }

Flexus.pluralize("human")
  # => "foo"
```

IMO this kind of behaviors can be source of bugs.

---

Given I wasn't aware of Flexus, I started to work on a Inflecto fork for the dry-rb ecosystem. The idea is to use the same inflection library both for Hanami and ROM. You can find it at: https://github.com/jodosha/dry-inflector

It exposes the same interface (aka features), but at the instance level. So exceptions are set at the instance level, and they aren't mutable.

```ruby
require "dry/inflector"

inflector = Dry::Inflector.new do |i|
  i.plural "virus", "viruses"
end

inflector.pluralize("virus")
  # => "viruses"

# Since now on, there is no way to change the exceptions. The program is deterministic.
```

---

I suspect that the singleton pattern used by Inflecto/Flexus can be source of slowness. I measured `dry-inflector` and `inflecto`, for basic pluralization `dry-inflector` is 5x faster: https://gist.github.com/jodosha/42f1ac5d2c8b71aa8dfb3a42f31bb1b8

---

My question is: would you consider to move the API from class level to instance level? I think this is important to educate the community about the problems of the global state.

Thanks for listening. 💚 

/cc @solnic

**Comment by mbj** [comment]
@jodosha This is what I'm advocating for initially. The reason it did not exist in inflecto was that I that time was only packaging the code without any changes.

Back in the time I even think that @solnic and I discussed alternatives (instance based) and he had gone for it because of that discussions.

**Comment by abinoam** [comment]
I completely agree about having a "per instance" approach. The current one, as stated above, is surely a source of bugs.

I have done something similar at HighLine gem (one of the related PRs is at https://github.com/JEG2/highline/pull/214/files).
We have changed the api recommending creating an instance and using it.
For back compatibility we just create one instance to be used by the HighLine class methods.

**Comment by abinoam** [comment]
If the projects have the same goals and have similar roadmaps to achieve them, I would even consider merging them. ("Merge" can just abandon one in favor of the other).

As I said to @Ptico I'm not able to be **the only in charge** of a project like this, but I really want to be a core contributor. So, as @Ptico took the front position, I have readily helped him on it and my intentions are to keep helping.

So, I would just let @Ptico decide the path we should take. Any path you all and @Ptico decide I'll be here to help with code, management and so.

One question more, is Dry::Inflector ready? Would it be ready for a pre release?

**Comment by Ptico** [comment]
I'm thinking about to move all the logic to the module or even module builder (see: #7) and then include it to the class. And yes, I think it should be a class with possible fallback like 
```ruby
Inflecto = Flexus.new(Flexus::Configuration::DEFAULT)
```

**Comment by jodosha** [comment]
After a discussion with dry-rb folks, we decided that _dry_ was the perfect home for this project, because we're talking about a focused lib.

The final goal are: 1. make a general purpose lib for the Ruby ecosystem 2. adopt it in Hanami and ROM.

---

That `dry-inflector` has the same features of `inflecto`, plus a few rules from `hanami-utils` (`Hanami::Utils::Inflector`). I haven't ported the class loading features, because IMO they don't belong to an inflector lib.

---

So yes, it's ready for a pre-release, but.. Given both `dry-inflector` and `flexus` are both a tentative to resume `inflecto`, it makes no sense to duplicate the effort. We can work together.

Regarding the home and the name of the merged project, you (@Ptico, @abinoam, and @solnic decide). It can be `flexus` or `dry-inflector`.

You can take the code that I wrote and do whatever you want. Or not. It's up to you.

From the Hanami perspective, we need an immutable, instance based inflection lib. That's it.

Again, in the spirit of OSS, I'd really love if we're able to work together on one lib. 💚

**Comment by solnic** [comment]
FWIW, I think if we put it under dry, it should get more contributions, as the org is already relatively well known

**Comment by Ptico** [comment]
@solnic i'm happy with this (dry-inflector) as long as @abinoam agree

**Comment by Ptico** [comment]
The only thing that i wish to provide smooth migration for existing inflecto users. Let's discuss how we can achieve this.

**Comment by mbj** [comment]
> The only thing that i wish to provide smooth migration for existing inflecto users. Let's discuss how we can achieve this.

I'd assume the majority of inflecto users right now do not modify the preset. Hence if you'd create a compatibility wrapper that raises on the inflecto mutating APIs you likely get the best of both worlds.

**Comment by abinoam** [comment]
I have (pre) agreed with anything you decide @Ptico! 

I think we should release a stable flexus version and point people to dry-inflector. This will give a no gap timeline for people coming from inflecto.

And @solnic and @jodosha, just tell us how you want us to help on dry-inflector.

**Comment by Ptico** [comment]
@abinoam Great, let's move on! It would be much better for community and gem itself.

**Comment by abinoam** [comment]
> for basic pluralization dry-inflector is 5x faster: https://gist.github.com/jodosha/42f1ac5d2c8b71aa8dfb3a42f31bb1b8
> @jodosha 

I was not able to repeat the results @jodosha.

See my fork of your gist.
https://gist.github.com/abinoam/24e0308e11bcbd5873f7aa7a3251155b

It uses the master branch of dry-inflector, inflecto and the no_global branch of flexus (the one at #20).

Basically dry-inflector is 1,3x slower than flexus/inflecto at this bench for pluralizations. BUT... I think this doesn't reflect the truth.

The bench would only be valid if we compared the same set of pluralization/singularization rules.
And I think you have added more default rules to dry-inflector
When comparing something that doesn't depend on the number of rules like ```underscorization``` all options fall into the same performance.
