### ISSUE TITLE
Travis build is not passing

### ISSUE THREAD

**Issue by abinoam** [Ptico/inflecto#4]
@Ptico I'll work on this.

**Comment by Ptico** [comment]
@abinoam I don't think that this subclassing core methods is always the bad idea, but yeah, this can be fixed in v0.2.0 to not break the inflecto 0.0.2 compatibility somehow.

Let's add a temporary exception in reek.yml and create a task for 0.2.0

**Comment by abinoam** [comment]
I have fixed it already. Git pushing it.

**Comment by abinoam** [comment]
And yes, let's do a "stable" release with the least changes possible. Then we grow up from there.
First pass is a green build.

**Comment by abinoam** [comment]
Fixed at #10
