### ISSUE TITLE
Version numbering

### ISSUE THREAD

**Issue by abinoam** [Ptico/inflecto#9]
@Ptico what do you think about beginning version numbers **from** the last version of the original repo? 0.1.0.

So our first release could be 0.1.1.

**Comment by abinoam** [comment]
So you would have to change the milestones name.

**Comment by Ptico** [comment]
The last version on rubygems is 0.0.2, but yes, some people could refer to '0.1.0' via git

**Comment by Ptico** [comment]
Well, from the other side, we don't break 0.1.0 functionallity

**Comment by abinoam** [comment]
Yes. We do a first 0.1.1 release without breaking anything.

**Comment by Ptico** [comment]
Done in #8

**Comment by abinoam** [comment]
@Ptico at #18 I have bumped up the version to 1.0.0.
I thought better and renaming Inflecto module to Flexus module is a api breaking change.
So we should go up to 1.0.x. What do you think?
